### ISSUE TITLE
cannot load embed: malformed module path "embed": missing dot in first path element

### ISSUE THREAD

**Issue by cesarvspr** [pjvds/tunl#5]
So I just cloned the repo and tried the "_go get ./..._" inside the cmd folder. 

**But I got:**

> build github.com/pjvds/tunl/cmd: cannot load embed: malformed module path "embed": missing dot in first path element.

I'm new to go, how can I setup the workspace to start contributing to the project?

**Comment by newfotune** [comment]
What version of go are you using? You'll need to upgrade to go1.16. The `embed` package is part of go1.16

**Comment by pjvds** [comment]
Tunl is currently using the [`embed`](https://pkg.go.dev/embed) package that is [introduced ](https://golang.org/doc/go1.16#library-embed)by the freshly released go1.16: 

Make sure you [install go1.16](https://golang.org/dl/
) and try to run `go get ./...` again. If you need to use multiple go version I recommend to use [goenv](https://github.com/syndbg/goenv).

**Comment by aakash4dev** [comment]
I got same error, 
install a newer version of GoLang removed my issue. it may also work for you.
